stages:
- build
- test
- sonarQube

build:
  stage: build
  script:
    - cd individualproject
    - ./gradlew build
 
test:
  stage: test
  script:
    - cd individualproject
    - ./gradlew test

sonarQube:
  stage: sonarQube
  script:
    - cd individualproject
    - ./gradlew sonarqube -D "sonar.projectKey=individualproject" -D "sonar.host.url=http://localhost:9000" -D "sonar.login=ea558ec4403f773ed98ce19644d225ed8a69637b" --stacktrace
