stages:
- build
- test
- sonarQube

build:
  script:
    - cd individualproject
    - ./gradlew assemble
 
test:
  stage: test
  script:
    - cd individualproject
    - ./gradlew test

sonarQube:
  stage: sonarQube
  script:
    - cd individualproject
    - ./gradlew sonarqube
